package com.pos.domain;

public enum AuditEventType {
    LOGIN, LOGOUT, ACCOUNT_LOCKED, ACCOUNT_UNLOCKED,
    TRANSACTION_COMPLETED, TRANSACTION_VOIDED,
    REFUND_COMPLETED,
    PRODUCT_CREATED, PRODUCT_UPDATED, PRODUCT_DELETED,
    INVENTORY_ADJUSTED,
    DISCOUNT_APPLIED,
    SHIFT_OPENED, SHIFT_CLOSED
}
